version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
    # 如果后端也使用Docker，可以添加depends_on
    # depends_on:
    #   - backend
    
    # 可以挂载自定义nginx配置
    # volumes:
    #   - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf:ro

# 如果后端也要用Docker部署，可以添加后端服务
# services:
#   backend:
#     image: your-backend-image:latest
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_PROFILES_ACTIVE=prod
#     restart: unless-stopped